### ISSUE TITLE
line numbers shifted down when displaying code

### ISSUE THREAD

**Issue by tantignac** [jgm/gitit#264]
I put python code on my gitit using:

``` markdown
~~~ {.python .numberLines}
[code]
~~
```

(There is actually 3 tildes at the end but the GitHub parsing seems not to allow to display more than 2 tildes in a code example.)

For convenience, I write here the HTML source code produced:

``` html
<table class="sourceCode">
  <tbody>
    <tr>
      <td class="nums" title="Click to toggle line numbers">[code]</td>
      <td class="sourceCode">[code]</td>
    </tr>
  </tbody>
</table>
```

For the first `<td>`, here is the css used:

``` css
screen.css (line 42)
th, td {
    padding: 0.5em;
}
```

And for the second `<td>`, this css overrides the previous one:

``` css
hk-pyg.css (line 2)
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode, table.sourceCode pre {
    border: medium none;
    margin: 0;
    padding: 0;
    vertical-align: baseline;
}
```

The problem is that the cell containing the line numbers has a `padding-top` of `0.5em` whereas the one containing the code has a `padding-top`of `0em`. As a result, line numbers appear to be slightly shifted down in comparison to the code displayed.

Maybe is it an expected behaviour? If it is not the case, a way to solve this problem could be to make these two css more consistent...
