### ISSUE TITLE
Move discard button to the right

### ISSUE THREAD

**Issue by notnotrandom** [jgm/gitit#474]
I started to use gitit just recently (it's awesome!), but the one thing that almost got me several times was that, when editing, I almost clicked on discard... by mistake. Several times. So, in line with the principle suggested [here](http://blog.codinghorror.com/the-opposite-of-fitts-law/), I decided to move that button to the the right. The way I did it was by adding the following on `static/css/custom.css`:

``` css
/* put Discard button to the right, to avoid hitting it by mistake */
input[type="submit"]#cancel {
    padding: 1px;
    float: right;
}
```

But I thought it might important enough to suggest that it should be made the default layout? 

Anyway, those are my two cents. And have I mentioned gitit is awesome? :-)
