### ISSUE TITLE
No borders in tables.

### ISSUE THREAD

**Issue by capn-freako** [jgm/gitit#693]
I can't seem to get my tables to have borders, no matter what I try in `custom.css`.
Is there some trick to this?

Here's what I currently have in my `custom.css` file, regarding tables:

```css
table {
    padding-right: 0.6em;
    padding-left:  0.67em;
    margin: auto; /* center */
    text-align: center;
    /* Override border settings in reset-fonts-grids */
    border-collapse: collapse;
    border-spacing: 5px;
    border-width: 1px;
    border-color: black;
    border-style: solid;
}
td, th {
  border: 10px solid #333;
  padding: 0 .2em;
}
tr { vertical-align:middle; }
td { padding: 5px; text-align: center; }
img.bordered, table.bordered, td.bordered, .bordered-cells td {
    padding:10px;
    border:10px solid rgba(0,0,0,0.3);
    border-radius: 0.2em;
    background: rgba(255,255,0,0.015);
}
td img { width:100%; }
```
